# =============================================================================
# Hypridle Configuration
# https://wiki.hypr.land/Hypr-Ecosystem/hypridle/
# =============================================================================

general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display on resume.
}

# 2.5 min: Dim display backlight to save power
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# 5 min: Lock screen
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 5.5 min: Turn off display
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 30 min: Suspend system
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
